import { Geist, Geist_Mono,Bebas_Neue,Roboto,Source_Sans_3 } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: {default:"Photon",
    template: "%s | Photon",
  },
  template: "%s |Photon",
  description: "Generated by create next app",
};
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500"],

});

const sourceSans3 = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${bebasNeue.variable} ${roboto.variable} ${sourceSans3.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
